name: file_tree
description: Visualize the file tree of a directory.
version: 1.0.4
repository: https://github.com/CodeOTR/file_tree
homepage: https://codeontherocks.dev/
# flutter pub publish --dry-run

environment:
  sdk: ^3.1.0

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0
  args: ^2.4.2

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0

screenshots:
  - description: "Expand file tree with emojis"
    path: assets/icon.png

executables:
  tree: